### ISSUE TITLE
Dataloader is super slow

### ISSUE THREAD

**Issue by mwang625** [kakaobrain/nerf-factory#21]
Hi,

Thanks for the awesome framework for NeRF! I have a question about the data loader speed, what would be the expected time for loading shiny blender dataset for example? 
I'm using a NVIDIA T4 device with a single GPU and cuda 11.7, and the estimated loading time for testing data loader is around 4.5 hours. Here is the command I used to load your provided checkpoints, the config file is unchanged:
`python3 run.py --ginc configs/nerf/shiny_blender.gin --scene car --ginb run.run_train=False --ckpt_path logs/nerf_shiny_blender_car_220901/best.ckpt`
I created the conda environment as suggested in README, then also tried to upgrade to latest cuda toolkit, torch and torch lightning version for cuda11.7, in both cases the testing data loader needs more than 4 hours to load. 
I would really appreciate it if you can shed some light on this issue. Please let me know if you need more information. Thanks in advance!
![Screen Shot 2023-01-26 at 1 59 11 PM](https://user-images.githubusercontent.com/55957131/214841643-43f6c643-a5bd-4c1e-80ec-9ddf22e1d83e.png)

**Comment by jeongyw12382** [comment]
I do not think this is a problem. 
NeRF takes more than a minute to generate an image with a resolution of [800, 800] due to the computationally expensive volumetric rendering process. 
When evaluating on ShinyBlender, the code will evaluate an entire scene, which consists of more than a hundred frames. Accordingly, it should take more than several hours for testing. 
To handle this issue, I recommend the options below
- Reduce the number of points to sample while rendering. 
- Use a `test_skip` option to evaluate partial scenes.

**Comment by jeongyw12382** [comment]
Please reopen the issue if you have any further items to discuss.

**Comment by mwang625** [comment]
Thanks a lot for your explanations and suggestions! I thought the process bar is only the data loading, now it makes sense if it's the evaluation pipeline.
