### ISSUE TITLE
Question about NeRF dataset and MipNerf360 dataset

### ISSUE THREAD

**Issue by chufall** [kakaobrain/nerf-factory#23]
Hi, thank you for this work!

I  have a question of the dataloader of llff dataset and 360 dataset, which is very different!
In order to use nerf or mipnerf360, the method of prepare my own dataset is the same ,which is using COLMAP to prepross images . so why the load method is different?
By the way, in the function load_nerf_360_v2_data/nerf_360_v2.py， what's puerpose of calling "similarity_from_cameras"?    

Thanks  a lot!
qc

**Comment by jeongyw12382** [comment]
As we are integrating all NeRF-like models in a single repo, we have decided to use the same dataloader across the all models. `similarity_from_cameras` is quite crucial preprocess function in Plenoxels, since it normalizes camera trajectories from c2w cameras. This is the reference to follow-up:
https://github.com/sxyu/svox2/blob/ee80e2c4df8f29a407fda5729a494be94ccf9234/opt/util/util.py#L319

**Comment by jeongyw12382** [comment]
Feel free to reopen the issue when it is not resolved.
