### ISSUE TITLE
RefNeRF test stage PSNR Wrong

### ISSUE THREAD

**Issue by zpceng314** [kakaobrain/nerf-factory#25]
Hi！When I test the psnr of ref-nerf in ball scene， the checkpoint is the download from your open-source website. the psnr result is 10.56， but the rendering images are pretty good, so could you tell me the reason to the problem? Looking farward to your reply! Thanks!

Here is my run code:
nohup python3 run.py --ginc /paddle/zengpengcheng01/code/NeRF-Factory/configs/refnerf/shiny_blender.gin --scene_name ball --ginb run.run_train=False --ckpt_path logs/best.ckpt > test.log 2>&1

**Comment by jeongyw12382** [comment]
@seungjooshin Could you check for this issue?

**Comment by seungjooshin** [comment]
I have checked the result using your command and there is no problem.
If your result is wrong only for the ball scene, it is possible that the preprocessing might not be done. For the shiny blender dataset, only the ball scene has a different format of rendering images.

ball
- r_{#frame}.png: rgb
- r_{#frame}_alpha.png: alpha

otherwise
- r_{#frame}.png: rgba (rgb + alpha)

Thus, we convert rendering images of ball scene from rgb + alpha to rgba.

https://github.com/kakaobrain/nerf-factory/blob/31d74696afc89c23609e81d20c7c2eabc3f1c928/scripts/download_data.sh#L52-L58

If you also get the same wrong results with the preprocessed ball scene, please provide more details about your environmental setting.

**Comment by zpceng314** [comment]
Thanks for your reply, I have solved it!
