### ISSUE TITLE
Training example from docs is giving error

### ISSUE THREAD

**Issue by mishig25** [kakaobrain/nerf-factory#7]
When you run `python3 run.py --ginc configs/nerf/blender.gin --scene chair` as suggested in https://kakaobrain.github.io/NeRF-Factory/docs/installation/#training-code, [this line](https://github.com/kakaobrain/NeRF-Factory/blob/f61bb8744a5cb4820a4d968fb3bfbed777550f4a/src/data/interface.py#L60) is failing:

```
AttributeError: 'Trainer' object has no attribute 'num_devices'
  In call to configurable 'run' (<function run at 0x7f76abbdcb80>)

    fn(*args, **kwargs)
  File "/home/mishig/NeRF-Factory/src/data/interface.py", line 60, in setup
    self.num_devices = self.trainer.num_devices
AttributeError: 'Trainer' object has no attribute 'num_devices'
  In call to configurable 'run' (<function run at 0x7f7dca95ca60>)
```

Thanks in advance! 👍

**Comment by jeongyw12382** [comment]
This error is mainly due to the version of pytorch-lightning. We have changed the lightning version after making the project page. Could you retry the same command after preparing a conda environment using the uploaded conda env file? 
```
conda env create --file nerf_factory.yml
```
We will quickly update the installation code in the project page. Sorry for the confusion.
