### ISSUE TITLE
Documentation on training speed

### ISSUE THREAD

**Issue by akshay-krishnan** [kakaobrain/nerf-factory#8]
Thanks for creating and maintaining this great library! 
I was wondering if you have stats for the time taken to train the different models on one of the standard datasets documented somewhere. If not, these would be useful for reference and comparisons.

**Comment by seungjooshin** [comment]
Thank you for your great suggestion :)
We will prepare additional docs for the training time on the next release. 
If you wanna compare the training time of the models right now, you can check it through the log files (TensorBoard).
See [here](https://huggingface.co/nrtf/nerf_factory).

**Comment by jeongyw12382** [comment]
We have finally decided not to add a documentation for training speed due to the reasons below:
1. The training speed varies depending on the environment where we run the code. As an example, we found the number of CPUs also changes the training time. 
2. As we are running the code on our shared resources, the training time changes depending on the number of programs that are running on the cluster. 

For these reasons, we could not fairly compare the performance. Moreover, the training speed could not be easily reproduced in a new environment, indicating this score is meaningless when a new user starts new work on a new environment.

Please let us know if you have any further issues.

**Comment by akshay-krishnan** [comment]
Thanks for the update! I agree that it is not reproducible across environments, but what I was interested in was relative time taken by different methods. 
It may not be too important, so its okay to not do it if such an experiment would be nontrivial to set up.
